version: '3'

services:
  # Service 1: Node.js Web Application
  nodejs_web_app:
    build:
      context: ./node-microservice
    ports:
      - "8081:8081"  # Map container port 8081 to host port 8081
    networks:
      - my_network
    depends_on:
      - python_flask_app
    environment:
      - FLASK_HOST=python_flask_app
      - FLASK_PORT=5000
      - HOST=0.0.0.0
      - PORT=8081

  # Service 2: Python Flask Application
  python_flask_app:
    build:
      context: ./python-microservice
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    networks:
      - my_network

#  # Service 3: PostgreSQL Database
#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: testdb
#      POSTGRES_USER: test_user
#      POSTGRES_PASSWORD: test_password
#    ports:
#      - "5432:5432"  # Map container port 5432 to host port 5432
#    networks:
#      - my_network

networks:
  my_network:
    driver: bridge
